### ISSUE TITLE
How do 3 ebytes work together?

### ISSUE THREAD

**Issue by aspartech** [xreef/EByte_LoRa_E32_circuitpython_library#1]
Hello, I need to use 3 ebytes for a project and 1 ebyte must communicate with all of them. Also, the data needs to go every 1 second. We communicated 2 ebytes with a loop, but it worked very slowly and we could not add the 3rd ebyte. Thanks in advance.

**Comment by xreef** [comment]
Hi,
the speed is influenced by the noise, baud rate, air data rate, and distance and connection of AUX.
It can't be predeterminated, but you can disable some controls to do it better.
Bye Renzo
